[build]
  command = "npx pnpm build"
  publish = "dist"

[build.environment]
  NPM_FLAGS="--prefix=/dev/null"

[[plugins]]
  package = "./plugins/pnpm-preinstaller"

[[redirects]]
  from = "/"
  to = "/de/"
  force = true
  status = 302
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/"
  to = "/en/"
  force = true
  status = 302
