[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/de/"
  force = true
  status = 302
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/"
  to = "/en/"
  force = true
  status = 302
